import { Inter } from 'next/font/google'
import './globals.css'
import ThemeRegistry from '../../theme/ThemeRegistry'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// theme
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeRegistry>
      <body className={inter.className}>{children}</body>
      </ThemeRegistry>
    </html>
  )
}
